{
	"version": 1485113411,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/platform-sheet0.png",
		"images/player2-sheet0.png",
		"images/player2-sheet1.png",
		"images/switch-sheet0.png",
		"images/water-sheet0.png",
		"images/water-sheet1.png",
		"images/water-sheet2.png",
		"images/fire-sheet0.png",
		"images/shock-sheet0.png",
		"images/shock-sheet1.png",
		"images/shock-sheet2.png",
		"images/mountain-sheet0.png",
		"images/sky-sheet0.png",
		"images/mountais-sheet0.png",
		"images/wavewater-sheet0.png",
		"images/wavewater-sheet1.png",
		"images/wavewater-sheet2.png",
		"images/destroyer-sheet0.png",
		"images/firewave-sheet0.png",
		"images/firewave-sheet1.png",
		"images/firewave-sheet2.png",
		"images/shockwave-sheet0.png",
		"images/shockwave-sheet1.png",
		"media/agua - ativacao plataforma2.m4a",
		"media/agua - ativacao plataforma2.ogg",
		"media/agua - onda novo1.m4a",
		"media/agua - onda novo1.ogg",
		"media/eletrico - ativacao2.m4a",
		"media/eletrico - ativacao2.ogg",
		"media/eletrico - onda3.m4a",
		"media/eventos - vitoria.m4a",
		"media/eventos - vitoria.ogg",
		"media/fogo - ativacao plataforma2.m4a",
		"media/fogo - ativacao plataforma2.ogg",
		"media/fogo - onda2.m4a",
		"media/personagem - pulo3.m4a",
		"media/personagem - pulo3.ogg",
		"media/personagem - robo morrendo.m4a",
		"media/personagem - robo morrendo.ogg",
		"media/splash.m4a",
		"media/splash.ogg",
		"media/switch - on.m4a",
		"media/eletrico - onda3.ogg",
		"media/fogo - onda2.ogg",
		"media/switch - on.ogg",
		"media/personagem - pulo4.m4a",
		"media/personagem - pulo4.ogg",
		"media/background2.m4a",
		"media/background2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}